version: "3.7"

services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: develop
    environment:
      - DB_URL=ecto://postgres:postgres@db:5432/nisse_dev
      - SECRET_KEY_BASE
      - SIGNING_SALT
    ports:
      - "4000:4000"
