apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: nisse
build:
  #local:
  #  push: true
  artifacts:
    - image: ghcr.io/ilkka/nisse/nisse
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/db.yaml
    - k8s/web.yaml
