apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: nisse
build:
  #local:
  #  push: true
  artifacts:
    - image: ghcr.io/ilkka/nisse/nisse
      docker:
        dockerfile: Dockerfile
portForward:
  - resourceType: Service
    resourceName: web
    port: 4000
    localPort: 4000
manifests:
  rawYaml:
    # For some reason having this here does _not_ ensure that CRDs get installed before
    # deploying the operator
    #- https://raw.githubusercontent.com/mysql/mysql-operator/trunk/deploy/deploy-crds.yaml
    #- https://raw.githubusercontent.com/mysql/mysql-operator/trunk/deploy/deploy-operator.yaml
    #- k8s/db-mysql.yaml
    - k8s/db-postgres.yaml
    - k8s/web.yaml
