apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  ports:
    - port: 4000
      name: http
  type: LoadBalancer
  selector:
    app: web

---
apiVersion: v1
kind: Secret
metadata:
  name: web-secrets
data:
  secret-key-base: MkdSSEtqdzgxZXJvbXNnODZBRkZCcjJ4eGlTWkRDZkh6ZkZDNEZTVE5YbDF1RHVucVE0OFJ2S01tSUZFR04zcA==
  signing-salt: NzhOZ3pCY20xMnhrYk9FVnc4UFVDRDQ3VHlsbm9IWVQxNDgyWjlud1d5SGpUek1kRmFOMWgrNkpFSkFzZGJOdQ==

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: ghcr.io/ilkka/nisse/nisse
          ports:
            - containerPort: 4000
          resources:
            limits:
              cpu: 500m
              memory: 3G
          env:
            - name: WEB_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: postgresql-password
            - name: DB_URL
              value: "ecto://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@pgpool-svc.$(WEB_NAMESPACE).svc.cluster.local:5432/nisse"
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: web-secrets
                  key: secret-key-base
            - name: SIGNING_SALT
              valueFrom:
                secretKeyRef:
                  name: web-secrets
                  key: signing-salt
      initContainers:
        - name: wait-for-dbms
          image: docker.io/bitnami/postgresql-repmgr:11.12.0-debian-10-r44
          command: ["bash", "-c", "until psql -h pgpool-svc.$(WEB_NAMESPACE).svc.cluster.local -U $(POSTGRES_USER) -d postgres -c 'SELECT 1'; do echo 'waiting for db'; sleep 2; done"]
          resources:
            limits:
              cpu: 500m
              memory: 512M
          env:
            - name: WEB_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POSTGRES_USER
              value: "postgres"
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: postgresql-password
        - name: create-db
          image: docker.io/bitnami/postgresql-repmgr:11.12.0-debian-10-r44
          command: ["bash", "-c", "psql -h pgpool-svc.$(WEB_NAMESPACE).svc.cluster.local -U $(POSTGRES_USER) -d postgres -c 'CREATE DATABASE $(POSTGRES_DB);' || true"]
          resources:
            limits:
              cpu: 500m
              memory: 512M
          env:
            - name: WEB_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POSTGRES_USER
              value: "postgres"
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: postgresql-password
            - name: POSTGRES_DB
              value: "nisse"
        - name: migrate-db
          image: ghcr.io/ilkka/nisse/nisse
          command: ["/app/nisse/bin/nisse", "eval", "Nisse.Release.migrate"]
          resources:
            limits:
              cpu: 500m
              memory: 2G
          env:
            - name: MIX_ENV
              value: prod
            - name: WEB_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POSTGRES_USER
              value: "postgres"
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: postgresql-password
            - name: DB_URL
              value: "ecto://$(POSTGRES_USER):$(PGPASSWORD)@pgpool-svc.$(WEB_NAMESPACE).svc.cluster.local:5432/nisse"
            - name: SECRET_KEY_BASE
              value: ''
            - name: SIGNING_SALT
              value: ''
