name: Build and push

on:
  push:
    branches: [trunk]

jobs:
  build:
    name: Build and publish image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push
        uses: docker/build-push-action@v1.1.0
        with:
          username: ilkka
          password: ${{ github.token }}
          registry: docker.pkg.github.com
          repository: ilkka/nisse/nisse
          cache_froms: docker.pkg.github.com/ilkka/nisse/nisse:latest
          tags: latest
          tag_with_ref: false
          tag_with_sha: false
          target: deploy
          add_git_labels: true
          push: true
