name: Build and push

on:
  push:
    branches: [trunk]

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build and publish image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and push
        uses: docker/build-push-action@v5.3.0
        with:
          username: ilkka
          password: ${{ github.token }}
          registry: ghcr.io
          repository: ilkka/nisse/nisse
          cache_froms: ghcr.io/ilkka/nisse/nisse:latest
          tags: latest
          tag_with_ref: false
          tag_with_sha: false
          target: deploy
          add_git_labels: true
          push: true
