name: Docs
on:
  push:
    branches: [ trunk ]

jobs:
  docs:
    runs-on: ubuntu-latest
    env:
        UML_FILES: ".wsd"
        OUTPUT_DIR: "docs"
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Get changed UML files
      id: getfile
      run: |
        echo "::set-output name=files::$(git diff-tree -r --no-commit-id --name-only ${{ github.sha }} | grep ${{ env.UML_FILES }} | xargs)"
    - name: Make sure output directory exists
      run: mkdir -p ${{ env.OUTPUT_DIR }}
    - name: Generate PNG Diagrams
      uses: cloudbees/plantuml-github-action@v1.1.0
      with:
        args: -v -tpng -o ${{ env.OUTPUT_DIR }} ${{ steps.getfile.outputs.files }}
    - name: Push Local Changes
      uses:  stefanzweifel/git-auto-commit-action@v4.4.0
      with: 
        commit_message: "Update rendered PlantUML diagrams" 
        branch: ${{ github.head_ref }}
