name: Test PR

on:
  pull_request:
    branches: [trunk]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.14.1"
          otp-version: "25.1.2"
      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Setup PostgreSQL
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          # Version of PostgreSQL to use
          postgresql version: "12"
          # POSTGRES_DB - name for the default database that is created
          postgresql db: nisse_test
          # POSTGRES_USER - create the specified user with superuser power
          postgresql user: nisse
          # POSTGRES_PASSWORD - superuser password
          postgresql password: nisse
      - name: Install dependencies
        run: mix deps.get
      - name: Run tests
        run: mix test
        env:
          DB_URL: "ecto://nisse:nisse@localhost:5432/nisse_test"
          SECRET_KEY_BASE: "rU3X/+Fw60UYALcN51sAtD+c3jFSjjSsCSY83IGmaJywiwiSVyNnepYKZSPYO0Uv"
          SIGNING_SALT: "5bb1LGNuwb8LHpHAMTtG9HCdg5VJbYBoNy/etC88WjbEHhZqbRuBiiQSaSzZZroE"
